name: phples
recipe: symfony
config:
  php: '8.1'
  via: nginx
  webroot: public
  database: mariadb
  xdebug: true
services:
  database:
    portforward: 3321
    type: mariadb
  phpmyadmin:
    type: phpmyadmin
  node:
    type: node:16
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
  watch:
    service: node
    description: watch frontend code changes
    cmd:
      - npm run watch

