name: phples
recipe: symfony
config:
  php: '8.1'
  via: nginx
  webroot: public
  database: mariadb
  xdebug: true
services:
  database:
    portforward: 3321
    type: mariadb
  phpmyadmin:
    type: phpmyadmin
